import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { PageInner } from "./components/PageInner";
import { SiteHeader } from "./components/layout/SiteHeader";
import { SiteFooter } from "./components/layout/SiteFooter";
import { VideoPlayer } from "./components/VideoPlayer";

const geistSans = localFont({
  src: "../../public/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "../../public/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header className="w-full">
          <PageInner>
            <SiteHeader />
          </PageInner>
        </header>

        
        <main className="w-full">
          <PageInner>
            {children}
          </PageInner>
        </main>

        <VideoPlayer />

        <footer className="w-full">
          <PageInner>
            <SiteFooter />
          </PageInner>
        </footer>
      </body>
    </html>
  );
}

